/**
 * PPT Generator — generates Python scripts that use python-pptx
 * to create real .pptx presentations.
 *
 * CC uses write_file to save the script, then execute_shell to run it.
 */

const STYLES = {
  minimal: { primary: '2D3436', accent: '0984E3', bg: 'FFFFFF' },
  vibrant: { primary: '6C5CE7', accent: 'FD79A8', bg: 'FFFFFF' },
  dark: { primary: 'DFE6E9', accent: '74B9FF', bg: '2D3436' },
  nature: { primary: '27AE60', accent: 'F39C12', bg: 'FFFFFF' },
};

/**
 * Generate a complete Python script that creates a PPTX file.
 * @param {Object} options
 * @param {string} options.title - Main title
 * @param {string} options.subtitle - Subtitle text
 * @param {Array<{title: string, bulletPoints: string[], notes?: string}>} options.slides
 * @param {string} options.outputPath - Where to save the .pptx file
 * @param {string} [options.style='vibrant'] - Color style
 */
export function generatePPTXScript(options) {
  const { title, subtitle, slides, outputPath, style = 'vibrant' } = options;
  const colors = STYLES[style] || STYLES.vibrant;

  // Escape strings for Python
  const esc = (str) => (str || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');

  let slidesCode = '';

  // Title slide
  slidesCode += `# --- 封面 ---
slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
add_bg(slide, "${colors.bg}")
# Title text
txBox = slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(8), Inches(1.5))
tf = txBox.text_frame
tf.word_wrap = True
p = tf.paragraphs[0]
p.text = "${esc(title)}"
p.font.size = Pt(40)
p.font.bold = True
p.font.color.rgb = hex_to_rgb("${colors.primary}")
p.alignment = PP_ALIGN.CENTER

# Subtitle
txBox2 = slide.shapes.add_textbox(Inches(1.5), Inches(4.2), Inches(7), Inches(1))
tf2 = txBox2.text_frame
tf2.word_wrap = True
p2 = tf2.paragraphs[0]
p2.text = "${esc(subtitle)}"
p2.font.size = Pt(18)
p2.font.color.rgb = hex_to_rgb("${colors.accent}")
p2.alignment = PP_ALIGN.CENTER

# Divider line
line = slide.shapes.add_shape(
    MSO_SHAPE.RECTANGLE, Inches(3), Inches(5.5), Inches(4), Pt(3)
)
line.fill.solid()
line.fill.fore_color.rgb = hex_to_rgb("${colors.accent}")
line.line.fill.background()
\n`;

  // Content slides
  for (let i = 0; i < slides.length; i++) {
    const s = slides[i];
    const slideNum = i + 2;
    let pointsArr = s.bulletPoints || [];
    let ptsCode = '';
    for (let j = 0; j < pointsArr.length; j++) {
      ptsCode += `  p = tf.add_paragraph()
  p.text = "${esc(pointsArr[j])}"
  p.font.size = Pt(16)
  p.font.color.rgb = hex_to_rgb("2D3436")
  p.space_after = Pt(12)
  p.level = 0
`;
    }

    slidesCode += `# --- 第${slideNum}页: ${esc(s.title)} ---
slide = prs.slides.add_slide(prs.slide_layouts[6])
add_bg(slide, "${colors.bg}")

# Slide title
txBox = slide.shapes.add_textbox(Inches(0.8), Inches(0.5), Inches(8.4), Inches(0.8))
tf = txBox.text_frame
tf.word_wrap = True
p = tf.paragraphs[0]
p.text = "${esc(s.title)}"
p.font.size = Pt(28)
p.font.bold = True
p.font.color.rgb = hex_to_rgb("${colors.primary}")

# Title underline
line = slide.shapes.add_shape(
    MSO_SHAPE.RECTANGLE, Inches(0.8), Inches(1.3), Inches(2), Pt(4)
)
line.fill.solid()
line.fill.fore_color.rgb = hex_to_rgb("${colors.accent}")
line.line.fill.background()

# Content bullets
txBox2 = slide.shapes.add_textbox(Inches(1), Inches(1.8), Inches(8), Inches(4.5))
tf2 = txBox2.text_frame
tf2.word_wrap = True
p0 = tf2.paragraphs[0]
p0.text = ""
${ptsCode}
# Page number
add_page_number(slide, ${slideNum}, "${colors.primary}")
\n`;
  }

  // Build full script
  const script = `# -*- coding: utf-8 -*-
"""Generated by CC — AI PPT Creator"""
import sys
import os

try:
    from pptx import Presentation
    from pptx.util import Inches, Pt, Emu
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN
    from pptx.enum.shapes import MSO_SHAPE
except ImportError:
    print("正在安装 python-pptx...")
    os.system(f"{sys.executable} -m pip install python-pptx -q")
    from pptx import Presentation
    from pptx.util import Inches, Pt, Emu
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN
    from pptx.enum.shapes import MSO_SHAPE

def hex_to_rgb(h):
    h = h.lstrip('#')
    return RGBColor(int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))

def add_bg(slide, color):
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = hex_to_rgb(color)

def add_page_number(slide, num, color):
    txBox = slide.shapes.add_textbox(Inches(4.5), Inches(5.1), Inches(1), Inches(0.4))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = str(num)
    p.font.size = Pt(10)
    p.font.color.rgb = hex_to_rgb(color)
    p.alignment = PP_ALIGN.CENTER

# Create presentation (16:9)
prs = Presentation()
prs.slide_width = Inches(10)
prs.slide_height = Inches(5.625)

${slidesCode}
# Save
output = "${esc(outputPath)}"
os.makedirs(os.path.dirname(output), exist_ok=True)
prs.save(output)
print(f"PPT已保存: {output}")
print(f"共 {len(prs.slides)} 页")
`;

  return script;
}

/**
 * Generate a simple Python script for PPT from a topic outline.
 * This is a convenience wrapper that creates slides from a list of {title, content} objects.
 */
export function generatePPTXFromOutline(topic, outlineItems, outputPath, style = 'vibrant') {
  const slides = outlineItems.map(item => ({
    title: item.title,
    bulletPoints: item.content.split('\n').filter(line => line.trim()),
  }));

  return generatePPTXScript({
    title: topic,
    subtitle: `由CC智能生成 · ${new Date().toLocaleDateString('zh-CN')}`,
    slides,
    outputPath,
    style,
  });
}

/** Returns a prompt snippet for the LLM to plan PPT content. */
export const PPT_CONTENT_PROMPT = `
当用户要求做PPT时，请按以下格式规划内容：
1. 先简要说明PPT的主题和整体结构
2. 然后用以下格式列出每一页：
   - 页面标题
   - 要点（每行一个，用换行分隔）
3. 推荐风格（可选）：minimal / vibrant / dark / nature
4. 调用 write_file 将脚本保存为 .py 文件
5. 调用 execute_shell("python 脚本路径") 执行生成
`;
